// Mocks generated by Mockito 5.4.4 from annotations
// in app/test/tastes/logic/taste_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/core/exceptions/domain_exception.dart' as _i5;
import 'package:app/data/models/taste_list_model.dart' as _i6;
import 'package:app/domain/obtain_taste_list_use_case.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ObtainTasteListUseCaseUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockObtainTasteListUseCaseUseCase extends _i1.Mock
    implements _i3.ObtainTasteListUseCaseUseCase {
  @override
  _i4.Future<_i2.Either<_i5.DomainException, _i6.TasteListModel>> call(
          String? offset) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [offset],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.DomainException, _i6.TasteListModel>>.value(
            _FakeEither_0<_i5.DomainException, _i6.TasteListModel>(
          this,
          Invocation.method(
            #call,
            [offset],
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.DomainException, _i6.TasteListModel>>.value(
            _FakeEither_0<_i5.DomainException, _i6.TasteListModel>(
          this,
          Invocation.method(
            #call,
            [offset],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DomainException, _i6.TasteListModel>>);
}
